### PR TITLE
feat: compress images at git stage

### LINKED ISSUE #497: [Feature Request] Only compress images added to the Git stage
As a developer, the images that need to be compressed are often newly added rather than the previous. A feature that only compresses images added to Git stage would be very useful.

### PR DESCRIPTION
**Pull request by nieyuyao**
closes #497

### CODE REVIEW

**Comment by andi1984** [comment]
@nieyuyao Thanks in advance for your PR and I do not see any bigger issue while testing it. I just made some small comments to maybe split the work up into a testable helper.

Shame on myself: I should have done this to the existing code as well and will do. Don't get me wrong on this. But if you have time capacity, you could maybe start within this PR? If not I can take care of this.

**Comment by nieyuyao** [comment]
@andi1984 Thanks for your reply. Do you mean splitting `extension.ts` into different modules?

**Comment by andi1984** [comment]
> into some modules

Exactly, maybe we could have some `helper` folder with helper functions each in a file that can also be tested.

As I said, I can take this over, but if you want and you have time, you could start by extracting this string manipulation `replace(...).split(...).filter(...)` into such a helper file/function.

**Comment by nieyuyao** [comment]
Oh, I see.It's probably better if you take it. ❤️

**Pull request merged**
